import Section from "@/components/ui/Section";
import { Star, Users, ChartNoAxesColumnIncreasing } from "lucide-react";

const playlists = [
  {
    icon: Star,
    title: "Editorial Playlists",
    description:
      "The big ones—curated directly by streaming platform teams. High exposure, competitive, and genre-specific.",
    examples: "Examples: RapCaviar, Today's Top Hits, New Music Friday",
  },
  {
    icon: Users,
    title: "Independent Playlists",
    description:
      "Curated by influential taste-makers, bloggers, and music lovers with engaged followings.",
    examples: "Examples: Genre-specific curators, music blog playlists",
  },
  {
    icon: ChartNoAxesColumnIncreasing,
    title: "Algorithmic Playlists",
    description:
      "Generated by platform algorithms based on listening habits. Placement comes from engagement signals.",
    examples: "Examples: Discover Weekly, Release Radar, Daily Mixes",
  },
];

export default function TypesPage() {
  return (
    <Section className="bg-card/30">
      <div className="container-tight">
        <div className="text-center mb-16">
          <span className="text-primary font-medium text-sm uppercase tracking-widest mb-4 block">
            Playlist Types
          </span>
          <h2 className="font-display text-3xl md:text-4xl font-bold text-foreground mb-6">
            Understanding the Playlist Landscape
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Different playlists serve different purposes. Here&apos;s what you
            need to know.
          </p>
        </div>

        <div className="grid md:grid-cols-3 gap-8">
          {playlists.map((item, idx) => {
            const Icon = item.icon;
            return (
              <div
                key={idx}
                className="p-8 rounded-xl bg-background border border-border"
              >
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-6">
                  <Icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="font-display font-semibold text-xl text-foreground mb-3">
                  {item.title}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed mb-4">
                  {item.description}
                </p>
                <p className="text-xs text-muted-foreground italic">
                  {item.examples}
                </p>
              </div>
            );
          })}
        </div>
      </div>
    </Section>
  );
}
